-- Create test users for all custom roles
-- Password: Test123! (capital T, exclamation mark)
-- Created: 2026-02-19 16:40
-- Updated: 2026-02-20 00:30 - Fixed password hash (was placeholder, now valid WordPress hash)
-- Note: IDs will auto-increment from next available ID

-- ⚠️ IMPORTANT: This file uses ON DUPLICATE KEY UPDATE to be idempotent
-- If users already exist, their passwords will NOT be reset (safer for production)
-- To reset passwords, delete users first or update manually

-- Password hash for 'Test123!' - bcrypt hash generated by WordPress
-- Updated: 2026-02-20 - Replaced placeholder with actual working hash
-- Hash format: $wp$2y$10$ (WordPress PHPass with bcrypt)
SET @password_hash = '$wp$2y$10$WarkvfqQixx1vz/sdjO4B.A1GNZCYnOg3epUtf6lpBiAWiS8QsKbK';

-- Insert test users (IDs will be auto-assigned)
-- User meta will be added after INSERT to get correct user IDs

-- Candidate test user
INSERT INTO wp_users (user_login, user_pass, user_nicename, user_email, user_registered, user_status, display_name)
VALUES ('candidate_test', @password_hash, 'candidate_test', 'candidate_test@talendelight.com', NOW(), 0, 'Test Candidate')
ON DUPLICATE KEY UPDATE user_nicename='candidate_test', user_email='candidate_test@talendelight.com', display_name='Test Candidate';
SET @candidate_id = LAST_INSERT_ID();
INSERT INTO wp_usermeta (user_id, meta_key, meta_value) VALUES
(@candidate_id, 'wp_capabilities', 'a:1:{s:12:"td_candidate";b:1;}'),
(@candidate_id, 'wp_user_level', '0'),
(@candidate_id, 'nickname', 'candidate_test'),
(@candidate_id, 'first_name', 'Test'),
(@candidate_id, 'last_name', 'Candidate');
  
INSERT INTO wp_users (user_login, user_pass, user_nicename, user_email, user_registered, user_status, display_name)
VALUES ('employer_test', @password_hash, 'employer_test', 'employer_test@talendelight.com', NOW(), 0, 'Test Employer')
ON DUPLICATE KEY UPDATE user_nicename='employer_test', user_email='employer_test@talendelight.com', display_name='Test Employer';
SET @employer_id = LAST_INSERT_ID();
INSERT INTO wp_usermeta (user_id, meta_key, meta_value) VALUES
(@employer_id, 'wp_capabilities', 'a:1:{s:11:"td_employer";b:1;}'),
(@employer_id, 'wp_user_level', '0'),
(@employer_id, 'nickname', 'employer_test'),
(@employer_id, 'first_name', 'Test'),
(@employer_id, 'last_name', 'Employer');

-- Scout test user
INSERT INTO wp_users (user_login, user_pass, user_nicename, user_email, user_registered, user_status, display_name)
VALUES ('scout_test', @password_hash, 'scout_test', 'scout_test@talendelight.com', NOW(), 0, 'Test Scout')
ON DUPLICATE KEY UPDATE user_nicename='scout_test', user_email='scout_test@talendelight.com', display_name='Test Scout';
SET @scout_id = LAST_INSERT_ID();
INSERT INTO wp_usermeta (user_id, meta_key, meta_value) VALUES
(@scout_id, 'wp_capabilities', 'a:1:{s:8:"td_scout";b:1;}'),
(@scout_id, 'wp_user_level', '0'),
(@scout_id, 'nickname', 'scout_test'),
(@scout_id, 'first_name', 'Test'),
(@scout_id, 'last_name', 'Scout');

-- Operator test user
INSERT INTO wp_users (user_login, user_pass, user_nicename, user_email, user_registered, user_status, display_name)
VALUES ('operator_test', @password_hash, 'operator_test', 'operator_test@talendelight.com', NOW(), 0, 'Test Operator')
ON DUPLICATE KEY UPDATE user_nicename='operator_test', user_email='operator_test@talendelight.com', display_name='Test Operator';
SET @operator_id = LAST_INSERT_ID();
INSERT INTO wp_usermeta (user_id, meta_key, meta_value) VALUES
(@operator_id, 'wp_capabilities', 'a:1:{s:11:"td_operator";b:1;}'),
(@operator_id, 'wp_user_level', '0'),
(@operator_id, 'nickname', 'operator_test'),
(@operator_id, 'first_name', 'Test'),
(@operator_id, 'last_name', 'Operator');

-- Manager test user
INSERT INTO wp_users (user_login, user_pass, user_nicename, user_email, user_registered, user_status, display_name)
VALUES ('manager_test', @password_hash, 'manager_test', 'manager_test@talendelight.com', NOW(), 0, 'Test Manager')
ON DUPLICATE KEY UPDATE user_nicename='manager_test', user_email='manager_test@talendelight.com', display_name='Test Manager';
SET @manager_id = LAST_INSERT_ID();
INSERT INTO wp_usermeta (user_id, meta_key, meta_value) VALUES
(@manager_id, 'wp_capabilities', 'a:1:{s:10:"td_manager";b:1;}'),
(@manager_id, 'wp_user_level', '0'),
(@manager_id, 'nickname', 'manager_test'),
(@manager_id, 'first_name', 'Test'),
(@manager_id, 'last_name', 'Manager');

-- Note: Password hash used above is for 'Test123!'
-- All test users share the same password for convenience in development

-- ⚠️ ALTERNATIVE: Use WP-CLI to create/reset test users (recommended for password reset)
-- podman exec wp bash -c "
-- wp user create candidate_test candidate_test@talendelight.com --role=td_candidate --user_pass='Test123!' --display_name='Test Candidate' --first_name='Test' --last_name='Candidate' --allow-root
-- wp user create employer_test employer_test@talendelight.com --role=td_employer --user_pass='Test123!' --display_name='Test Employer' --first_name='Test' --last_name='Employer' --allow-root
-- wp user create scout_test scout_test@talendelight.com --role=td_scout --user_pass='Test123!' --display_name='Test Scout' --first_name='Test' --last_name='Scout' --allow-root
-- wp user create operator_test operator_test@talendelight.com --role=td_operator --user_pass='Test123!' --display_name='Test Operator' --first_name='Test' --last_name='Operator' --allow-root
-- wp user create manager_test manager_test@talendelight.com --role=td_manager --user_pass='Test123!' --display_name='Test Manager' --first_name='Test' --last_name='Manager' --allow-root
-- "
